/**
 * This class is generated by jOOQ
 */
package com.gogo.schema.tables.records;


import com.gogo.schema.tables.BbOrderItem;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BbOrderItemRecord extends UpdatableRecordImpl<BbOrderItemRecord> implements Record13<Long, Long, Long, Long, String, String, BigDecimal, Integer, BigDecimal, Long, Long, Byte, Long> {

    private static final long serialVersionUID = 77550539;

    /**
     * Setter for <code>bb.bb_order_item.order_item_no</code>.
     */
    public void setOrderItemNo(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>bb.bb_order_item.order_item_no</code>.
     */
    public Long getOrderItemNo() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>bb.bb_order_item.order_no</code>.
     */
    public void setOrderNo(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>bb.bb_order_item.order_no</code>.
     */
    public Long getOrderNo() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>bb.bb_order_item.product_no</code>.
     */
    public void setProductNo(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>bb.bb_order_item.product_no</code>.
     */
    public Long getProductNo() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>bb.bb_order_item.product_style_no</code>.
     */
    public void setProductStyleNo(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>bb.bb_order_item.product_style_no</code>.
     */
    public Long getProductStyleNo() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>bb.bb_order_item.product_name</code>.
     */
    public void setProductName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bb.bb_order_item.product_name</code>.
     */
    public String getProductName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bb.bb_order_item.product_style_name</code>.
     */
    public void setProductStyleName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bb.bb_order_item.product_style_name</code>.
     */
    public String getProductStyleName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>bb.bb_order_item.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>bb.bb_order_item.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>bb.bb_order_item.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>bb.bb_order_item.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>bb.bb_order_item.total_amount</code>.
     */
    public void setTotalAmount(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>bb.bb_order_item.total_amount</code>.
     */
    public BigDecimal getTotalAmount() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>bb.bb_order_item.create_time</code>.
     */
    public void setCreateTime(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>bb.bb_order_item.create_time</code>.
     */
    public Long getCreateTime() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>bb.bb_order_item.update_time</code>.
     */
    public void setUpdateTime(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>bb.bb_order_item.update_time</code>.
     */
    public Long getUpdateTime() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>bb.bb_order_item.delete_flag</code>. 0-NO,1-YES
     */
    public void setDeleteFlag(Byte value) {
        set(11, value);
    }

    /**
     * Getter for <code>bb.bb_order_item.delete_flag</code>. 0-NO,1-YES
     */
    public Byte getDeleteFlag() {
        return (Byte) get(11);
    }

    /**
     * Setter for <code>bb.bb_order_item.delete_time</code>.
     */
    public void setDeleteTime(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>bb.bb_order_item.delete_time</code>.
     */
    public Long getDeleteTime() {
        return (Long) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Long, Long, Long, Long, String, String, BigDecimal, Integer, BigDecimal, Long, Long, Byte, Long> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Long, Long, Long, Long, String, String, BigDecimal, Integer, BigDecimal, Long, Long, Byte, Long> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return BbOrderItem.BB_ORDER_ITEM.ORDER_ITEM_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return BbOrderItem.BB_ORDER_ITEM.ORDER_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return BbOrderItem.BB_ORDER_ITEM.PRODUCT_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return BbOrderItem.BB_ORDER_ITEM.PRODUCT_STYLE_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return BbOrderItem.BB_ORDER_ITEM.PRODUCT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return BbOrderItem.BB_ORDER_ITEM.PRODUCT_STYLE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return BbOrderItem.BB_ORDER_ITEM.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return BbOrderItem.BB_ORDER_ITEM.QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field9() {
        return BbOrderItem.BB_ORDER_ITEM.TOTAL_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return BbOrderItem.BB_ORDER_ITEM.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return BbOrderItem.BB_ORDER_ITEM.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field12() {
        return BbOrderItem.BB_ORDER_ITEM.DELETE_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field13() {
        return BbOrderItem.BB_ORDER_ITEM.DELETE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getOrderItemNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getOrderNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getProductNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getProductStyleNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getProductName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getProductStyleName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value9() {
        return getTotalAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value12() {
        return getDeleteFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value13() {
        return getDeleteTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderItemRecord value1(Long value) {
        setOrderItemNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderItemRecord value2(Long value) {
        setOrderNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderItemRecord value3(Long value) {
        setProductNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderItemRecord value4(Long value) {
        setProductStyleNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderItemRecord value5(String value) {
        setProductName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderItemRecord value6(String value) {
        setProductStyleName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderItemRecord value7(BigDecimal value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderItemRecord value8(Integer value) {
        setQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderItemRecord value9(BigDecimal value) {
        setTotalAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderItemRecord value10(Long value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderItemRecord value11(Long value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderItemRecord value12(Byte value) {
        setDeleteFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderItemRecord value13(Long value) {
        setDeleteTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderItemRecord values(Long value1, Long value2, Long value3, Long value4, String value5, String value6, BigDecimal value7, Integer value8, BigDecimal value9, Long value10, Long value11, Byte value12, Long value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BbOrderItemRecord
     */
    public BbOrderItemRecord() {
        super(BbOrderItem.BB_ORDER_ITEM);
    }

    /**
     * Create a detached, initialised BbOrderItemRecord
     */
    public BbOrderItemRecord(Long orderItemNo, Long orderNo, Long productNo, Long productStyleNo, String productName, String productStyleName, BigDecimal price, Integer quantity, BigDecimal totalAmount, Long createTime, Long updateTime, Byte deleteFlag, Long deleteTime) {
        super(BbOrderItem.BB_ORDER_ITEM);

        set(0, orderItemNo);
        set(1, orderNo);
        set(2, productNo);
        set(3, productStyleNo);
        set(4, productName);
        set(5, productStyleName);
        set(6, price);
        set(7, quantity);
        set(8, totalAmount);
        set(9, createTime);
        set(10, updateTime);
        set(11, deleteFlag);
        set(12, deleteTime);
    }
}
