/**
 * This class is generated by jOOQ
 */
package com.gogo.schema.tables.records;


import com.gogo.schema.tables.BbOrder;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BbOrderRecord extends UpdatableRecordImpl<BbOrderRecord> implements Record10<Long, Byte, Integer, BigDecimal, Byte, String, Long, Long, Byte, Long> {

    private static final long serialVersionUID = 706551610;

    /**
     * Setter for <code>bb.bb_order.order_no</code>.
     */
    public void setOrderNo(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>bb.bb_order.order_no</code>.
     */
    public Long getOrderNo() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>bb.bb_order.status</code>.
     */
    public void setStatus(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>bb.bb_order.status</code>.
     */
    public Byte getStatus() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>bb.bb_order.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>bb.bb_order.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>bb.bb_order.total_amount</code>.
     */
    public void setTotalAmount(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>bb.bb_order.total_amount</code>.
     */
    public BigDecimal getTotalAmount() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>bb.bb_order.pay_type</code>. 1-deliveryCash
     */
    public void setPayType(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>bb.bb_order.pay_type</code>. 1-deliveryCash
     */
    public Byte getPayType() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>bb.bb_order.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bb.bb_order.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>bb.bb_order.create_time</code>.
     */
    public void setCreateTime(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>bb.bb_order.create_time</code>.
     */
    public Long getCreateTime() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>bb.bb_order.update_time</code>.
     */
    public void setUpdateTime(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>bb.bb_order.update_time</code>.
     */
    public Long getUpdateTime() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>bb.bb_order.delete_flag</code>. 0-NO,1-YES
     */
    public void setDeleteFlag(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>bb.bb_order.delete_flag</code>. 0-NO,1-YES
     */
    public Byte getDeleteFlag() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>bb.bb_order.delete_time</code>.
     */
    public void setDeleteTime(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>bb.bb_order.delete_time</code>.
     */
    public Long getDeleteTime() {
        return (Long) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Byte, Integer, BigDecimal, Byte, String, Long, Long, Byte, Long> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Byte, Integer, BigDecimal, Byte, String, Long, Long, Byte, Long> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return BbOrder.BB_ORDER.ORDER_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field2() {
        return BbOrder.BB_ORDER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return BbOrder.BB_ORDER.QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return BbOrder.BB_ORDER.TOTAL_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return BbOrder.BB_ORDER.PAY_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return BbOrder.BB_ORDER.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return BbOrder.BB_ORDER.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return BbOrder.BB_ORDER.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return BbOrder.BB_ORDER.DELETE_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return BbOrder.BB_ORDER.DELETE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getOrderNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value2() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getTotalAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getPayType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getDeleteFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getDeleteTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderRecord value1(Long value) {
        setOrderNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderRecord value2(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderRecord value3(Integer value) {
        setQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderRecord value4(BigDecimal value) {
        setTotalAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderRecord value5(Byte value) {
        setPayType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderRecord value6(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderRecord value7(Long value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderRecord value8(Long value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderRecord value9(Byte value) {
        setDeleteFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderRecord value10(Long value) {
        setDeleteTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderRecord values(Long value1, Byte value2, Integer value3, BigDecimal value4, Byte value5, String value6, Long value7, Long value8, Byte value9, Long value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BbOrderRecord
     */
    public BbOrderRecord() {
        super(BbOrder.BB_ORDER);
    }

    /**
     * Create a detached, initialised BbOrderRecord
     */
    public BbOrderRecord(Long orderNo, Byte status, Integer quantity, BigDecimal totalAmount, Byte payType, String description, Long createTime, Long updateTime, Byte deleteFlag, Long deleteTime) {
        super(BbOrder.BB_ORDER);

        set(0, orderNo);
        set(1, status);
        set(2, quantity);
        set(3, totalAmount);
        set(4, payType);
        set(5, description);
        set(6, createTime);
        set(7, updateTime);
        set(8, deleteFlag);
        set(9, deleteTime);
    }
}
