/**
 * This class is generated by jOOQ
 */
package com.gogo.schema.tables.records;


import com.gogo.schema.tables.BbOrderAddress;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BbOrderAddressRecord extends UpdatableRecordImpl<BbOrderAddressRecord> implements Record12<Long, Long, String, String, String, String, String, String, Long, Long, Byte, Long> {

    private static final long serialVersionUID = 1449886858;

    /**
     * Setter for <code>bb.bb_order_address.address_no</code>.
     */
    public void setAddressNo(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>bb.bb_order_address.address_no</code>.
     */
    public Long getAddressNo() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>bb.bb_order_address.order_no</code>.
     */
    public void setOrderNo(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>bb.bb_order_address.order_no</code>.
     */
    public Long getOrderNo() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>bb.bb_order_address.user_name</code>.
     */
    public void setUserName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bb.bb_order_address.user_name</code>.
     */
    public String getUserName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bb.bb_order_address.user_phone</code>.
     */
    public void setUserPhone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bb.bb_order_address.user_phone</code>.
     */
    public String getUserPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bb.bb_order_address.province_name</code>.
     */
    public void setProvinceName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bb.bb_order_address.province_name</code>.
     */
    public String getProvinceName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bb.bb_order_address.city_name</code>.
     */
    public void setCityName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bb.bb_order_address.city_name</code>.
     */
    public String getCityName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>bb.bb_order_address.area_name</code>.
     */
    public void setAreaName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>bb.bb_order_address.area_name</code>.
     */
    public String getAreaName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>bb.bb_order_address.address</code>.
     */
    public void setAddress(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>bb.bb_order_address.address</code>.
     */
    public String getAddress() {
        return (String) get(7);
    }

    /**
     * Setter for <code>bb.bb_order_address.create_time</code>.
     */
    public void setCreateTime(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>bb.bb_order_address.create_time</code>.
     */
    public Long getCreateTime() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>bb.bb_order_address.update_time</code>.
     */
    public void setUpdateTime(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>bb.bb_order_address.update_time</code>.
     */
    public Long getUpdateTime() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>bb.bb_order_address.delete_flag</code>. 0-NO,1-YES
     */
    public void setDeleteFlag(Byte value) {
        set(10, value);
    }

    /**
     * Getter for <code>bb.bb_order_address.delete_flag</code>. 0-NO,1-YES
     */
    public Byte getDeleteFlag() {
        return (Byte) get(10);
    }

    /**
     * Setter for <code>bb.bb_order_address.delete_time</code>.
     */
    public void setDeleteTime(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>bb.bb_order_address.delete_time</code>.
     */
    public Long getDeleteTime() {
        return (Long) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, Long, String, String, String, String, String, String, Long, Long, Byte, Long> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, Long, String, String, String, String, String, String, Long, Long, Byte, Long> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return BbOrderAddress.BB_ORDER_ADDRESS.ADDRESS_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return BbOrderAddress.BB_ORDER_ADDRESS.ORDER_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BbOrderAddress.BB_ORDER_ADDRESS.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return BbOrderAddress.BB_ORDER_ADDRESS.USER_PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return BbOrderAddress.BB_ORDER_ADDRESS.PROVINCE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return BbOrderAddress.BB_ORDER_ADDRESS.CITY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return BbOrderAddress.BB_ORDER_ADDRESS.AREA_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return BbOrderAddress.BB_ORDER_ADDRESS.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return BbOrderAddress.BB_ORDER_ADDRESS.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return BbOrderAddress.BB_ORDER_ADDRESS.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field11() {
        return BbOrderAddress.BB_ORDER_ADDRESS.DELETE_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return BbOrderAddress.BB_ORDER_ADDRESS.DELETE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getAddressNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getOrderNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUserPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getProvinceName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCityName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getAreaName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value11() {
        return getDeleteFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getDeleteTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderAddressRecord value1(Long value) {
        setAddressNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderAddressRecord value2(Long value) {
        setOrderNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderAddressRecord value3(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderAddressRecord value4(String value) {
        setUserPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderAddressRecord value5(String value) {
        setProvinceName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderAddressRecord value6(String value) {
        setCityName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderAddressRecord value7(String value) {
        setAreaName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderAddressRecord value8(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderAddressRecord value9(Long value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderAddressRecord value10(Long value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderAddressRecord value11(Byte value) {
        setDeleteFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderAddressRecord value12(Long value) {
        setDeleteTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderAddressRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6, String value7, String value8, Long value9, Long value10, Byte value11, Long value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BbOrderAddressRecord
     */
    public BbOrderAddressRecord() {
        super(BbOrderAddress.BB_ORDER_ADDRESS);
    }

    /**
     * Create a detached, initialised BbOrderAddressRecord
     */
    public BbOrderAddressRecord(Long addressNo, Long orderNo, String userName, String userPhone, String provinceName, String cityName, String areaName, String address, Long createTime, Long updateTime, Byte deleteFlag, Long deleteTime) {
        super(BbOrderAddress.BB_ORDER_ADDRESS);

        set(0, addressNo);
        set(1, orderNo);
        set(2, userName);
        set(3, userPhone);
        set(4, provinceName);
        set(5, cityName);
        set(6, areaName);
        set(7, address);
        set(8, createTime);
        set(9, updateTime);
        set(10, deleteFlag);
        set(11, deleteTime);
    }
}
