/**
 * This class is generated by jOOQ
 */
package com.gogo.schema.tables.records;


import com.gogo.schema.tables.BbProduct;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BbProductRecord extends UpdatableRecordImpl<BbProductRecord> implements Record7<Long, String, BigDecimal, Long, Long, Byte, Long> {

    private static final long serialVersionUID = 610877908;

    /**
     * Setter for <code>bb.bb_product.product_no</code>.
     */
    public void setProductNo(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>bb.bb_product.product_no</code>.
     */
    public Long getProductNo() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>bb.bb_product.product_name</code>.
     */
    public void setProductName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bb.bb_product.product_name</code>.
     */
    public String getProductName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bb.bb_product.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>bb.bb_product.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>bb.bb_product.create_time</code>.
     */
    public void setCreateTime(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>bb.bb_product.create_time</code>.
     */
    public Long getCreateTime() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>bb.bb_product.update_time</code>.
     */
    public void setUpdateTime(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>bb.bb_product.update_time</code>.
     */
    public Long getUpdateTime() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>bb.bb_product.delete_flag</code>. 0-NO,1-YES
     */
    public void setDeleteFlag(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>bb.bb_product.delete_flag</code>. 0-NO,1-YES
     */
    public Byte getDeleteFlag() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>bb.bb_product.delete_time</code>.
     */
    public void setDeleteTime(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>bb.bb_product.delete_time</code>.
     */
    public Long getDeleteTime() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, BigDecimal, Long, Long, Byte, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, BigDecimal, Long, Long, Byte, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return BbProduct.BB_PRODUCT.PRODUCT_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BbProduct.BB_PRODUCT.PRODUCT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return BbProduct.BB_PRODUCT.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return BbProduct.BB_PRODUCT.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return BbProduct.BB_PRODUCT.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return BbProduct.BB_PRODUCT.DELETE_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return BbProduct.BB_PRODUCT.DELETE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getProductNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProductName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getDeleteFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getDeleteTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbProductRecord value1(Long value) {
        setProductNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbProductRecord value2(String value) {
        setProductName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbProductRecord value3(BigDecimal value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbProductRecord value4(Long value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbProductRecord value5(Long value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbProductRecord value6(Byte value) {
        setDeleteFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbProductRecord value7(Long value) {
        setDeleteTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbProductRecord values(Long value1, String value2, BigDecimal value3, Long value4, Long value5, Byte value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BbProductRecord
     */
    public BbProductRecord() {
        super(BbProduct.BB_PRODUCT);
    }

    /**
     * Create a detached, initialised BbProductRecord
     */
    public BbProductRecord(Long productNo, String productName, BigDecimal price, Long createTime, Long updateTime, Byte deleteFlag, Long deleteTime) {
        super(BbProduct.BB_PRODUCT);

        set(0, productNo);
        set(1, productName);
        set(2, price);
        set(3, createTime);
        set(4, updateTime);
        set(5, deleteFlag);
        set(6, deleteTime);
    }
}
