/**
 * This class is generated by jOOQ
 */
package com.gogo.schema.tables.records;


import com.gogo.schema.tables.PayAppAccountCfg;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PayAppAccountCfgRecord extends UpdatableRecordImpl<PayAppAccountCfgRecord> implements Record7<String, String, String, String, String, Byte, String> {

    private static final long serialVersionUID = 1477901052;

    /**
     * Setter for <code>bb.pay_app_account_cfg.id</code>. id规则说明,1~6-realm/第6位/1-Android/2-iOS,7~9-onlinePayStyleNo/001-alipay/002-wechat,10~14-orderType
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>bb.pay_app_account_cfg.id</code>. id规则说明,1~6-realm/第6位/1-Android/2-iOS,7~9-onlinePayStyleNo/001-alipay/002-wechat,10~14-orderType
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>bb.pay_app_account_cfg.realm</code>. app版本realm
     */
    public void setRealm(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bb.pay_app_account_cfg.realm</code>. app版本realm
     */
    public String getRealm() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bb.pay_app_account_cfg.online_pay_style_no</code>. 支付方式
     */
    public void setOnlinePayStyleNo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bb.pay_app_account_cfg.online_pay_style_no</code>. 支付方式
     */
    public String getOnlinePayStyleNo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bb.pay_app_account_cfg.order_type</code>. 订单类型
     */
    public void setOrderType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bb.pay_app_account_cfg.order_type</code>. 订单类型
     */
    public String getOrderType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bb.pay_app_account_cfg.account_id</code>. 支付账号id,pay_partner_pay_method_cfg.id
     */
    public void setAccountId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bb.pay_app_account_cfg.account_id</code>. 支付账号id,pay_partner_pay_method_cfg.id
     */
    public String getAccountId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bb.pay_app_account_cfg.status</code>. 0-inactive,1-active
     */
    public void setStatus(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>bb.pay_app_account_cfg.status</code>. 0-inactive,1-active
     */
    public Byte getStatus() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>bb.pay_app_account_cfg.description</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>bb.pay_app_account_cfg.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, String, Byte, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, String, Byte, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return PayAppAccountCfg.PAY_APP_ACCOUNT_CFG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return PayAppAccountCfg.PAY_APP_ACCOUNT_CFG.REALM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PayAppAccountCfg.PAY_APP_ACCOUNT_CFG.ONLINE_PAY_STYLE_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return PayAppAccountCfg.PAY_APP_ACCOUNT_CFG.ORDER_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return PayAppAccountCfg.PAY_APP_ACCOUNT_CFG.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return PayAppAccountCfg.PAY_APP_ACCOUNT_CFG.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return PayAppAccountCfg.PAY_APP_ACCOUNT_CFG.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRealm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOnlinePayStyleNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getOrderType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayAppAccountCfgRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayAppAccountCfgRecord value2(String value) {
        setRealm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayAppAccountCfgRecord value3(String value) {
        setOnlinePayStyleNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayAppAccountCfgRecord value4(String value) {
        setOrderType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayAppAccountCfgRecord value5(String value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayAppAccountCfgRecord value6(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayAppAccountCfgRecord value7(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayAppAccountCfgRecord values(String value1, String value2, String value3, String value4, String value5, Byte value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PayAppAccountCfgRecord
     */
    public PayAppAccountCfgRecord() {
        super(PayAppAccountCfg.PAY_APP_ACCOUNT_CFG);
    }

    /**
     * Create a detached, initialised PayAppAccountCfgRecord
     */
    public PayAppAccountCfgRecord(String id, String realm, String onlinePayStyleNo, String orderType, String accountId, Byte status, String description) {
        super(PayAppAccountCfg.PAY_APP_ACCOUNT_CFG);

        set(0, id);
        set(1, realm);
        set(2, onlinePayStyleNo);
        set(3, orderType);
        set(4, accountId);
        set(5, status);
        set(6, description);
    }
}
