/**
 * This class is generated by jOOQ
 */
package com.gogo.schema.tables.records;


import com.gogo.schema.tables.TblUserRoleManager;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblUserRoleManagerRecord extends UpdatableRecordImpl<TblUserRoleManagerRecord> implements Record8<Long, String, String, Integer, String, Byte, Timestamp, String> {

    private static final long serialVersionUID = 1434096728;

    /**
     * Setter for <code>bb.tbl_user_role_manager.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>bb.tbl_user_role_manager.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>bb.tbl_user_role_manager.user_id</code>.
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bb.tbl_user_role_manager.user_id</code>.
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bb.tbl_user_role_manager.user_phone</code>.
     */
    public void setUserPhone(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bb.tbl_user_role_manager.user_phone</code>.
     */
    public String getUserPhone() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bb.tbl_user_role_manager.namespace_id</code>.
     */
    public void setNamespaceId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>bb.tbl_user_role_manager.namespace_id</code>.
     */
    public Integer getNamespaceId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>bb.tbl_user_role_manager.user_name</code>.
     */
    public void setUserName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bb.tbl_user_role_manager.user_name</code>.
     */
    public String getUserName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bb.tbl_user_role_manager.role_type</code>.
     */
    public void setRoleType(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>bb.tbl_user_role_manager.role_type</code>.
     */
    public Byte getRoleType() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>bb.tbl_user_role_manager.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>bb.tbl_user_role_manager.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>bb.tbl_user_role_manager.shop_no</code>. 店铺编号
     */
    public void setShopNo(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>bb.tbl_user_role_manager.shop_no</code>. 店铺编号
     */
    public String getShopNo() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, String, Integer, String, Byte, Timestamp, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, String, Integer, String, Byte, Timestamp, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TblUserRoleManager.TBL_USER_ROLE_MANAGER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TblUserRoleManager.TBL_USER_ROLE_MANAGER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TblUserRoleManager.TBL_USER_ROLE_MANAGER.USER_PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TblUserRoleManager.TBL_USER_ROLE_MANAGER.NAMESPACE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TblUserRoleManager.TBL_USER_ROLE_MANAGER.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return TblUserRoleManager.TBL_USER_ROLE_MANAGER.ROLE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return TblUserRoleManager.TBL_USER_ROLE_MANAGER.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TblUserRoleManager.TBL_USER_ROLE_MANAGER.SHOP_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUserPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getNamespaceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getRoleType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getShopNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblUserRoleManagerRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblUserRoleManagerRecord value2(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblUserRoleManagerRecord value3(String value) {
        setUserPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblUserRoleManagerRecord value4(Integer value) {
        setNamespaceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblUserRoleManagerRecord value5(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblUserRoleManagerRecord value6(Byte value) {
        setRoleType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblUserRoleManagerRecord value7(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblUserRoleManagerRecord value8(String value) {
        setShopNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblUserRoleManagerRecord values(Long value1, String value2, String value3, Integer value4, String value5, Byte value6, Timestamp value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblUserRoleManagerRecord
     */
    public TblUserRoleManagerRecord() {
        super(TblUserRoleManager.TBL_USER_ROLE_MANAGER);
    }

    /**
     * Create a detached, initialised TblUserRoleManagerRecord
     */
    public TblUserRoleManagerRecord(Long id, String userId, String userPhone, Integer namespaceId, String userName, Byte roleType, Timestamp createTime, String shopNo) {
        super(TblUserRoleManager.TBL_USER_ROLE_MANAGER);

        set(0, id);
        set(1, userId);
        set(2, userPhone);
        set(3, namespaceId);
        set(4, userName);
        set(5, roleType);
        set(6, createTime);
        set(7, shopNo);
    }
}
