/**
 * This class is generated by jOOQ
 */
package com.gogo.schema;


import com.gogo.schema.tables.BbOrder;
import com.gogo.schema.tables.BbOrderAddress;
import com.gogo.schema.tables.BbOrderItem;
import com.gogo.schema.tables.BbProduct;
import com.gogo.schema.tables.BbProductStyle;
import com.gogo.schema.tables.PayAppAccountCfg;
import com.gogo.schema.tables.TblUserRoleManager;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bb extends SchemaImpl {

    private static final long serialVersionUID = -484558216;

    /**
     * The reference instance of <code>bb</code>
     */
    public static final Bb BB = new Bb();

    /**
     * The table <code>bb.bb_order</code>.
     */
    public final BbOrder BB_ORDER = com.gogo.schema.tables.BbOrder.BB_ORDER;

    /**
     * The table <code>bb.bb_order_address</code>.
     */
    public final BbOrderAddress BB_ORDER_ADDRESS = com.gogo.schema.tables.BbOrderAddress.BB_ORDER_ADDRESS;

    /**
     * The table <code>bb.bb_order_item</code>.
     */
    public final BbOrderItem BB_ORDER_ITEM = com.gogo.schema.tables.BbOrderItem.BB_ORDER_ITEM;

    /**
     * The table <code>bb.bb_product</code>.
     */
    public final BbProduct BB_PRODUCT = com.gogo.schema.tables.BbProduct.BB_PRODUCT;

    /**
     * The table <code>bb.bb_product_style</code>.
     */
    public final BbProductStyle BB_PRODUCT_STYLE = com.gogo.schema.tables.BbProductStyle.BB_PRODUCT_STYLE;

    /**
     * The table <code>bb.pay_app_account_cfg</code>.
     */
    public final PayAppAccountCfg PAY_APP_ACCOUNT_CFG = com.gogo.schema.tables.PayAppAccountCfg.PAY_APP_ACCOUNT_CFG;

    /**
     * The table <code>bb.tbl_user_role_manager</code>.
     */
    public final TblUserRoleManager TBL_USER_ROLE_MANAGER = com.gogo.schema.tables.TblUserRoleManager.TBL_USER_ROLE_MANAGER;

    /**
     * No further instances allowed
     */
    private Bb() {
        super("bb", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            BbOrder.BB_ORDER,
            BbOrderAddress.BB_ORDER_ADDRESS,
            BbOrderItem.BB_ORDER_ITEM,
            BbProduct.BB_PRODUCT,
            BbProductStyle.BB_PRODUCT_STYLE,
            PayAppAccountCfg.PAY_APP_ACCOUNT_CFG,
            TblUserRoleManager.TBL_USER_ROLE_MANAGER);
    }
}
