/**
 * This class is generated by jOOQ
 */
package com.gogo.schema;


import com.gogo.schema.tables.BbOrder;
import com.gogo.schema.tables.BbOrderAddress;
import com.gogo.schema.tables.BbOrderItem;
import com.gogo.schema.tables.BbProduct;
import com.gogo.schema.tables.BbProductStyle;
import com.gogo.schema.tables.PayAppAccountCfg;
import com.gogo.schema.tables.TblUserRoleManager;
import com.gogo.schema.tables.records.BbOrderAddressRecord;
import com.gogo.schema.tables.records.BbOrderItemRecord;
import com.gogo.schema.tables.records.BbOrderRecord;
import com.gogo.schema.tables.records.BbProductRecord;
import com.gogo.schema.tables.records.BbProductStyleRecord;
import com.gogo.schema.tables.records.PayAppAccountCfgRecord;
import com.gogo.schema.tables.records.TblUserRoleManagerRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>bb</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<TblUserRoleManagerRecord, Long> IDENTITY_TBL_USER_ROLE_MANAGER = Identities0.IDENTITY_TBL_USER_ROLE_MANAGER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BbOrderRecord> KEY_BB_ORDER_PRIMARY = UniqueKeys0.KEY_BB_ORDER_PRIMARY;
    public static final UniqueKey<BbOrderAddressRecord> KEY_BB_ORDER_ADDRESS_PRIMARY = UniqueKeys0.KEY_BB_ORDER_ADDRESS_PRIMARY;
    public static final UniqueKey<BbOrderItemRecord> KEY_BB_ORDER_ITEM_PRIMARY = UniqueKeys0.KEY_BB_ORDER_ITEM_PRIMARY;
    public static final UniqueKey<BbProductRecord> KEY_BB_PRODUCT_PRIMARY = UniqueKeys0.KEY_BB_PRODUCT_PRIMARY;
    public static final UniqueKey<BbProductStyleRecord> KEY_BB_PRODUCT_STYLE_PRIMARY = UniqueKeys0.KEY_BB_PRODUCT_STYLE_PRIMARY;
    public static final UniqueKey<PayAppAccountCfgRecord> KEY_PAY_APP_ACCOUNT_CFG_PRIMARY = UniqueKeys0.KEY_PAY_APP_ACCOUNT_CFG_PRIMARY;
    public static final UniqueKey<TblUserRoleManagerRecord> KEY_TBL_USER_ROLE_MANAGER_PRIMARY = UniqueKeys0.KEY_TBL_USER_ROLE_MANAGER_PRIMARY;
    public static final UniqueKey<TblUserRoleManagerRecord> KEY_TBL_USER_ROLE_MANAGER_U_USERID_SHOPNO = UniqueKeys0.KEY_TBL_USER_ROLE_MANAGER_U_USERID_SHOPNO;
    public static final UniqueKey<TblUserRoleManagerRecord> KEY_TBL_USER_ROLE_MANAGER_U_USERPHONE_SHOPNO = UniqueKeys0.KEY_TBL_USER_ROLE_MANAGER_U_USERPHONE_SHOPNO;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<TblUserRoleManagerRecord, Long> IDENTITY_TBL_USER_ROLE_MANAGER = createIdentity(TblUserRoleManager.TBL_USER_ROLE_MANAGER, TblUserRoleManager.TBL_USER_ROLE_MANAGER.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<BbOrderRecord> KEY_BB_ORDER_PRIMARY = createUniqueKey(BbOrder.BB_ORDER, "KEY_bb_order_PRIMARY", BbOrder.BB_ORDER.ORDER_NO);
        public static final UniqueKey<BbOrderAddressRecord> KEY_BB_ORDER_ADDRESS_PRIMARY = createUniqueKey(BbOrderAddress.BB_ORDER_ADDRESS, "KEY_bb_order_address_PRIMARY", BbOrderAddress.BB_ORDER_ADDRESS.ADDRESS_NO);
        public static final UniqueKey<BbOrderItemRecord> KEY_BB_ORDER_ITEM_PRIMARY = createUniqueKey(BbOrderItem.BB_ORDER_ITEM, "KEY_bb_order_item_PRIMARY", BbOrderItem.BB_ORDER_ITEM.ORDER_ITEM_NO);
        public static final UniqueKey<BbProductRecord> KEY_BB_PRODUCT_PRIMARY = createUniqueKey(BbProduct.BB_PRODUCT, "KEY_bb_product_PRIMARY", BbProduct.BB_PRODUCT.PRODUCT_NO);
        public static final UniqueKey<BbProductStyleRecord> KEY_BB_PRODUCT_STYLE_PRIMARY = createUniqueKey(BbProductStyle.BB_PRODUCT_STYLE, "KEY_bb_product_style_PRIMARY", BbProductStyle.BB_PRODUCT_STYLE.PRODUCT_STYLE_NO);
        public static final UniqueKey<PayAppAccountCfgRecord> KEY_PAY_APP_ACCOUNT_CFG_PRIMARY = createUniqueKey(PayAppAccountCfg.PAY_APP_ACCOUNT_CFG, "KEY_pay_app_account_cfg_PRIMARY", PayAppAccountCfg.PAY_APP_ACCOUNT_CFG.ID);
        public static final UniqueKey<TblUserRoleManagerRecord> KEY_TBL_USER_ROLE_MANAGER_PRIMARY = createUniqueKey(TblUserRoleManager.TBL_USER_ROLE_MANAGER, "KEY_tbl_user_role_manager_PRIMARY", TblUserRoleManager.TBL_USER_ROLE_MANAGER.ID);
        public static final UniqueKey<TblUserRoleManagerRecord> KEY_TBL_USER_ROLE_MANAGER_U_USERID_SHOPNO = createUniqueKey(TblUserRoleManager.TBL_USER_ROLE_MANAGER, "KEY_tbl_user_role_manager_u_userId_shopNo", TblUserRoleManager.TBL_USER_ROLE_MANAGER.USER_ID, TblUserRoleManager.TBL_USER_ROLE_MANAGER.SHOP_NO);
        public static final UniqueKey<TblUserRoleManagerRecord> KEY_TBL_USER_ROLE_MANAGER_U_USERPHONE_SHOPNO = createUniqueKey(TblUserRoleManager.TBL_USER_ROLE_MANAGER, "KEY_tbl_user_role_manager_u_userPhone_shopNo", TblUserRoleManager.TBL_USER_ROLE_MANAGER.USER_PHONE, TblUserRoleManager.TBL_USER_ROLE_MANAGER.NAMESPACE_ID, TblUserRoleManager.TBL_USER_ROLE_MANAGER.SHOP_NO);
    }
}
