/**
 * This class is generated by jOOQ
 */
package com.gogo.schema;


import com.gogo.schema.tables.BbOrder;
import com.gogo.schema.tables.BbOrderAddress;
import com.gogo.schema.tables.BbOrderItem;
import com.gogo.schema.tables.BbProduct;
import com.gogo.schema.tables.BbProductStyle;
import com.gogo.schema.tables.PayAppAccountCfg;
import com.gogo.schema.tables.TblUserRoleManager;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in bb
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>bb.bb_order</code>.
     */
    public static final BbOrder BB_ORDER = com.gogo.schema.tables.BbOrder.BB_ORDER;

    /**
     * The table <code>bb.bb_order_address</code>.
     */
    public static final BbOrderAddress BB_ORDER_ADDRESS = com.gogo.schema.tables.BbOrderAddress.BB_ORDER_ADDRESS;

    /**
     * The table <code>bb.bb_order_item</code>.
     */
    public static final BbOrderItem BB_ORDER_ITEM = com.gogo.schema.tables.BbOrderItem.BB_ORDER_ITEM;

    /**
     * The table <code>bb.bb_product</code>.
     */
    public static final BbProduct BB_PRODUCT = com.gogo.schema.tables.BbProduct.BB_PRODUCT;

    /**
     * The table <code>bb.bb_product_style</code>.
     */
    public static final BbProductStyle BB_PRODUCT_STYLE = com.gogo.schema.tables.BbProductStyle.BB_PRODUCT_STYLE;

    /**
     * The table <code>bb.pay_app_account_cfg</code>.
     */
    public static final PayAppAccountCfg PAY_APP_ACCOUNT_CFG = com.gogo.schema.tables.PayAppAccountCfg.PAY_APP_ACCOUNT_CFG;

    /**
     * The table <code>bb.tbl_user_role_manager</code>.
     */
    public static final TblUserRoleManager TBL_USER_ROLE_MANAGER = com.gogo.schema.tables.TblUserRoleManager.TBL_USER_ROLE_MANAGER;
}
