/**
 * This class is generated by jOOQ
 */
package com.gogo.schema.tables;


import com.gogo.schema.Bb;
import com.gogo.schema.Keys;
import com.gogo.schema.tables.records.BbOrderAddressRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BbOrderAddress extends TableImpl<BbOrderAddressRecord> {

    private static final long serialVersionUID = 803657131;

    /**
     * The reference instance of <code>bb.bb_order_address</code>
     */
    public static final BbOrderAddress BB_ORDER_ADDRESS = new BbOrderAddress();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BbOrderAddressRecord> getRecordType() {
        return BbOrderAddressRecord.class;
    }

    /**
     * The column <code>bb.bb_order_address.address_no</code>.
     */
    public final TableField<BbOrderAddressRecord, Long> ADDRESS_NO = createField("address_no", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>bb.bb_order_address.order_no</code>.
     */
    public final TableField<BbOrderAddressRecord, Long> ORDER_NO = createField("order_no", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>bb.bb_order_address.user_name</code>.
     */
    public final TableField<BbOrderAddressRecord, String> USER_NAME = createField("user_name", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

    /**
     * The column <code>bb.bb_order_address.user_phone</code>.
     */
    public final TableField<BbOrderAddressRecord, String> USER_PHONE = createField("user_phone", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

    /**
     * The column <code>bb.bb_order_address.province_name</code>.
     */
    public final TableField<BbOrderAddressRecord, String> PROVINCE_NAME = createField("province_name", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

    /**
     * The column <code>bb.bb_order_address.city_name</code>.
     */
    public final TableField<BbOrderAddressRecord, String> CITY_NAME = createField("city_name", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

    /**
     * The column <code>bb.bb_order_address.area_name</code>.
     */
    public final TableField<BbOrderAddressRecord, String> AREA_NAME = createField("area_name", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

    /**
     * The column <code>bb.bb_order_address.address</code>.
     */
    public final TableField<BbOrderAddressRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR.length(512).nullable(false), this, "");

    /**
     * The column <code>bb.bb_order_address.create_time</code>.
     */
    public final TableField<BbOrderAddressRecord, Long> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>bb.bb_order_address.update_time</code>.
     */
    public final TableField<BbOrderAddressRecord, Long> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>bb.bb_order_address.delete_flag</code>. 0-NO,1-YES
     */
    public final TableField<BbOrderAddressRecord, Byte> DELETE_FLAG = createField("delete_flag", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "0-NO,1-YES");

    /**
     * The column <code>bb.bb_order_address.delete_time</code>.
     */
    public final TableField<BbOrderAddressRecord, Long> DELETE_TIME = createField("delete_time", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>bb.bb_order_address</code> table reference
     */
    public BbOrderAddress() {
        this("bb_order_address", null);
    }

    /**
     * Create an aliased <code>bb.bb_order_address</code> table reference
     */
    public BbOrderAddress(String alias) {
        this(alias, BB_ORDER_ADDRESS);
    }

    private BbOrderAddress(String alias, Table<BbOrderAddressRecord> aliased) {
        this(alias, aliased, null);
    }

    private BbOrderAddress(String alias, Table<BbOrderAddressRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Bb.BB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BbOrderAddressRecord> getPrimaryKey() {
        return Keys.KEY_BB_ORDER_ADDRESS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BbOrderAddressRecord>> getKeys() {
        return Arrays.<UniqueKey<BbOrderAddressRecord>>asList(Keys.KEY_BB_ORDER_ADDRESS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbOrderAddress as(String alias) {
        return new BbOrderAddress(alias, this);
    }

    /**
     * Rename this table
     */
    public BbOrderAddress rename(String name) {
        return new BbOrderAddress(name, null);
    }
}
