/**
 * This class is generated by jOOQ
 */
package com.gogo.schema.tables;


import com.gogo.schema.Bb;
import com.gogo.schema.Keys;
import com.gogo.schema.tables.records.BbProductStyleRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BbProductStyle extends TableImpl<BbProductStyleRecord> {

    private static final long serialVersionUID = 1479806481;

    /**
     * The reference instance of <code>bb.bb_product_style</code>
     */
    public static final BbProductStyle BB_PRODUCT_STYLE = new BbProductStyle();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BbProductStyleRecord> getRecordType() {
        return BbProductStyleRecord.class;
    }

    /**
     * The column <code>bb.bb_product_style.product_style_no</code>.
     */
    public final TableField<BbProductStyleRecord, Long> PRODUCT_STYLE_NO = createField("product_style_no", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>bb.bb_product_style.product_style_name</code>.
     */
    public final TableField<BbProductStyleRecord, String> PRODUCT_STYLE_NAME = createField("product_style_name", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>bb.bb_product_style.create_time</code>.
     */
    public final TableField<BbProductStyleRecord, Long> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>bb.bb_product_style.update_time</code>.
     */
    public final TableField<BbProductStyleRecord, Long> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>bb.bb_product_style.delete_flag</code>. 0-NO,1-YES
     */
    public final TableField<BbProductStyleRecord, Byte> DELETE_FLAG = createField("delete_flag", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "0-NO,1-YES");

    /**
     * The column <code>bb.bb_product_style.delete_time</code>.
     */
    public final TableField<BbProductStyleRecord, Long> DELETE_TIME = createField("delete_time", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>bb.bb_product_style</code> table reference
     */
    public BbProductStyle() {
        this("bb_product_style", null);
    }

    /**
     * Create an aliased <code>bb.bb_product_style</code> table reference
     */
    public BbProductStyle(String alias) {
        this(alias, BB_PRODUCT_STYLE);
    }

    private BbProductStyle(String alias, Table<BbProductStyleRecord> aliased) {
        this(alias, aliased, null);
    }

    private BbProductStyle(String alias, Table<BbProductStyleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Bb.BB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BbProductStyleRecord> getPrimaryKey() {
        return Keys.KEY_BB_PRODUCT_STYLE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BbProductStyleRecord>> getKeys() {
        return Arrays.<UniqueKey<BbProductStyleRecord>>asList(Keys.KEY_BB_PRODUCT_STYLE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbProductStyle as(String alias) {
        return new BbProductStyle(alias, this);
    }

    /**
     * Rename this table
     */
    public BbProductStyle rename(String name) {
        return new BbProductStyle(name, null);
    }
}
