/**
 * This class is generated by jOOQ
 */
package com.gogo.schema.tables;


import com.gogo.schema.Bb;
import com.gogo.schema.Keys;
import com.gogo.schema.tables.records.BbProductRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BbProduct extends TableImpl<BbProductRecord> {

    private static final long serialVersionUID = 1957477863;

    /**
     * The reference instance of <code>bb.bb_product</code>
     */
    public static final BbProduct BB_PRODUCT = new BbProduct();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BbProductRecord> getRecordType() {
        return BbProductRecord.class;
    }

    /**
     * The column <code>bb.bb_product.product_no</code>.
     */
    public final TableField<BbProductRecord, Long> PRODUCT_NO = createField("product_no", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>bb.bb_product.product_name</code>.
     */
    public final TableField<BbProductRecord, String> PRODUCT_NAME = createField("product_name", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>bb.bb_product.price</code>.
     */
    public final TableField<BbProductRecord, BigDecimal> PRICE = createField("price", org.jooq.impl.SQLDataType.DECIMAL.precision(10, 2).nullable(false), this, "");

    /**
     * The column <code>bb.bb_product.create_time</code>.
     */
    public final TableField<BbProductRecord, Long> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>bb.bb_product.update_time</code>.
     */
    public final TableField<BbProductRecord, Long> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>bb.bb_product.delete_flag</code>. 0-NO,1-YES
     */
    public final TableField<BbProductRecord, Byte> DELETE_FLAG = createField("delete_flag", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "0-NO,1-YES");

    /**
     * The column <code>bb.bb_product.delete_time</code>.
     */
    public final TableField<BbProductRecord, Long> DELETE_TIME = createField("delete_time", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>bb.bb_product</code> table reference
     */
    public BbProduct() {
        this("bb_product", null);
    }

    /**
     * Create an aliased <code>bb.bb_product</code> table reference
     */
    public BbProduct(String alias) {
        this(alias, BB_PRODUCT);
    }

    private BbProduct(String alias, Table<BbProductRecord> aliased) {
        this(alias, aliased, null);
    }

    private BbProduct(String alias, Table<BbProductRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Bb.BB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BbProductRecord> getPrimaryKey() {
        return Keys.KEY_BB_PRODUCT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BbProductRecord>> getKeys() {
        return Arrays.<UniqueKey<BbProductRecord>>asList(Keys.KEY_BB_PRODUCT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BbProduct as(String alias) {
        return new BbProduct(alias, this);
    }

    /**
     * Rename this table
     */
    public BbProduct rename(String name) {
        return new BbProduct(name, null);
    }
}
