/**
 * This class is generated by jOOQ
 */
package com.gogo.schema.tables;


import com.gogo.schema.Bb;
import com.gogo.schema.Keys;
import com.gogo.schema.tables.records.PayAppAccountCfgRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PayAppAccountCfg extends TableImpl<PayAppAccountCfgRecord> {

    private static final long serialVersionUID = -1416581442;

    /**
     * The reference instance of <code>bb.pay_app_account_cfg</code>
     */
    public static final PayAppAccountCfg PAY_APP_ACCOUNT_CFG = new PayAppAccountCfg();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PayAppAccountCfgRecord> getRecordType() {
        return PayAppAccountCfgRecord.class;
    }

    /**
     * The column <code>bb.pay_app_account_cfg.id</code>. id规则说明,1~6-realm/第6位/1-Android/2-iOS,7~9-onlinePayStyleNo/001-alipay/002-wechat,10~14-orderType
     */
    public final TableField<PayAppAccountCfgRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "id规则说明,1~6-realm/第6位/1-Android/2-iOS,7~9-onlinePayStyleNo/001-alipay/002-wechat,10~14-orderType");

    /**
     * The column <code>bb.pay_app_account_cfg.realm</code>. app版本realm
     */
    public final TableField<PayAppAccountCfgRecord, String> REALM = createField("realm", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "app版本realm");

    /**
     * The column <code>bb.pay_app_account_cfg.online_pay_style_no</code>. 支付方式
     */
    public final TableField<PayAppAccountCfgRecord, String> ONLINE_PAY_STYLE_NO = createField("online_pay_style_no", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "支付方式");

    /**
     * The column <code>bb.pay_app_account_cfg.order_type</code>. 订单类型
     */
    public final TableField<PayAppAccountCfgRecord, String> ORDER_TYPE = createField("order_type", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "订单类型");

    /**
     * The column <code>bb.pay_app_account_cfg.account_id</code>. 支付账号id,pay_partner_pay_method_cfg.id
     */
    public final TableField<PayAppAccountCfgRecord, String> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "支付账号id,pay_partner_pay_method_cfg.id");

    /**
     * The column <code>bb.pay_app_account_cfg.status</code>. 0-inactive,1-active
     */
    public final TableField<PayAppAccountCfgRecord, Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "0-inactive,1-active");

    /**
     * The column <code>bb.pay_app_account_cfg.description</code>.
     */
    public final TableField<PayAppAccountCfgRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

    /**
     * Create a <code>bb.pay_app_account_cfg</code> table reference
     */
    public PayAppAccountCfg() {
        this("pay_app_account_cfg", null);
    }

    /**
     * Create an aliased <code>bb.pay_app_account_cfg</code> table reference
     */
    public PayAppAccountCfg(String alias) {
        this(alias, PAY_APP_ACCOUNT_CFG);
    }

    private PayAppAccountCfg(String alias, Table<PayAppAccountCfgRecord> aliased) {
        this(alias, aliased, null);
    }

    private PayAppAccountCfg(String alias, Table<PayAppAccountCfgRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Bb.BB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PayAppAccountCfgRecord> getPrimaryKey() {
        return Keys.KEY_PAY_APP_ACCOUNT_CFG_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PayAppAccountCfgRecord>> getKeys() {
        return Arrays.<UniqueKey<PayAppAccountCfgRecord>>asList(Keys.KEY_PAY_APP_ACCOUNT_CFG_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayAppAccountCfg as(String alias) {
        return new PayAppAccountCfg(alias, this);
    }

    /**
     * Rename this table
     */
    public PayAppAccountCfg rename(String name) {
        return new PayAppAccountCfg(name, null);
    }
}
