/**
 * This class is generated by jOOQ
 */
package com.gogo.schema.tables;


import com.gogo.schema.Bb;
import com.gogo.schema.Keys;
import com.gogo.schema.tables.records.TblUserRoleManagerRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblUserRoleManager extends TableImpl<TblUserRoleManagerRecord> {

    private static final long serialVersionUID = -533748789;

    /**
     * The reference instance of <code>bb.tbl_user_role_manager</code>
     */
    public static final TblUserRoleManager TBL_USER_ROLE_MANAGER = new TblUserRoleManager();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblUserRoleManagerRecord> getRecordType() {
        return TblUserRoleManagerRecord.class;
    }

    /**
     * The column <code>bb.tbl_user_role_manager.id</code>.
     */
    public final TableField<TblUserRoleManagerRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>bb.tbl_user_role_manager.user_id</code>.
     */
    public final TableField<TblUserRoleManagerRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

    /**
     * The column <code>bb.tbl_user_role_manager.user_phone</code>.
     */
    public final TableField<TblUserRoleManagerRecord, String> USER_PHONE = createField("user_phone", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>bb.tbl_user_role_manager.namespace_id</code>.
     */
    public final TableField<TblUserRoleManagerRecord, Integer> NAMESPACE_ID = createField("namespace_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>bb.tbl_user_role_manager.user_name</code>.
     */
    public final TableField<TblUserRoleManagerRecord, String> USER_NAME = createField("user_name", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

    /**
     * The column <code>bb.tbl_user_role_manager.role_type</code>.
     */
    public final TableField<TblUserRoleManagerRecord, Byte> ROLE_TYPE = createField("role_type", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>bb.tbl_user_role_manager.create_time</code>.
     */
    public final TableField<TblUserRoleManagerRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>bb.tbl_user_role_manager.shop_no</code>. 店铺编号
     */
    public final TableField<TblUserRoleManagerRecord, String> SHOP_NO = createField("shop_no", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "店铺编号");

    /**
     * Create a <code>bb.tbl_user_role_manager</code> table reference
     */
    public TblUserRoleManager() {
        this("tbl_user_role_manager", null);
    }

    /**
     * Create an aliased <code>bb.tbl_user_role_manager</code> table reference
     */
    public TblUserRoleManager(String alias) {
        this(alias, TBL_USER_ROLE_MANAGER);
    }

    private TblUserRoleManager(String alias, Table<TblUserRoleManagerRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblUserRoleManager(String alias, Table<TblUserRoleManagerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Bb.BB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TblUserRoleManagerRecord, Long> getIdentity() {
        return Keys.IDENTITY_TBL_USER_ROLE_MANAGER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblUserRoleManagerRecord> getPrimaryKey() {
        return Keys.KEY_TBL_USER_ROLE_MANAGER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblUserRoleManagerRecord>> getKeys() {
        return Arrays.<UniqueKey<TblUserRoleManagerRecord>>asList(Keys.KEY_TBL_USER_ROLE_MANAGER_PRIMARY, Keys.KEY_TBL_USER_ROLE_MANAGER_U_USERID_SHOPNO, Keys.KEY_TBL_USER_ROLE_MANAGER_U_USERPHONE_SHOPNO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblUserRoleManager as(String alias) {
        return new TblUserRoleManager(alias, this);
    }

    /**
     * Rename this table
     */
    public TblUserRoleManager rename(String name) {
        return new TblUserRoleManager(name, null);
    }
}
